import type { Muscle, Settings } from '../../types';
import { BODY_FIGURES, type BodyFigure } from './bodyFigures';

/*
 * The muscle map's body: MuscleMap's artwork (bodyFigures.ts, generated by scripts/build-body-map.mjs from
 * github.com/melihcolpan/MuscleMap, MIT) turned into tappable muscle regions.
 *
 * Each figure is a list of layers in draw order: neutral body parts (head, hands, feet, knees, ankles, shins),
 * hair, and one region per Heft muscle. A region taps and labels as its own muscle, but it can also be LIT by
 * other muscles (shared lighting): it shows the highest intensity among them. cardio / other are never drawn.
 */

export type FigureSex = keyof typeof BODY_FIGURES;
export type FigureView = 'front' | 'back';

/**
 * Shared lighting: region muscle → the other muscles that also light it, per view. MuscleMap has no abductor
 * shape (the glutes stand in for the hip), and rows train the mid/lower traps under the back view's trapezius.
 */
export const ALSO_LIT_BY: Record<FigureView, Partial<Record<Muscle, readonly Muscle[]>>> = {
  front: { glutes: ['abductors'] },
  back: { glutes: ['abductors'], traps: ['upper_back'] },
};

export interface MapRegion {
  /** The muscle this region taps and labels as. */
  readonly muscle: Muscle;
  /** Muscles whose intensity lights the region (its own muscle first). */
  readonly lit: readonly Muscle[];
  readonly d: string;
}

export type MapLayer =
  | { readonly kind: 'body' | 'hair'; readonly d: string }
  | { readonly kind: 'muscle'; readonly region: MapRegion };

export interface MapFigure {
  /** viewBox `0 0 w h`; front and back of one sex share it, so they line up side by side. */
  readonly w: number;
  readonly h: number;
  /** Draw order (later layers paint over earlier ones). */
  readonly layers: readonly MapLayer[];
  readonly regions: readonly MapRegion[];
}

function toMapFigure(fig: BodyFigure, view: FigureView): MapFigure {
  const layers = fig.layers.map((l): MapLayer => {
    if (l.part === 'body' || l.part === 'hair') return { kind: l.part, d: l.d };
    return { kind: 'muscle', region: { muscle: l.part, lit: [l.part, ...(ALSO_LIT_BY[view][l.part] ?? [])], d: l.d } };
  });
  const regions = layers.flatMap((l) => (l.kind === 'muscle' ? [l.region] : []));
  return { w: fig.w, h: fig.h, layers, regions };
}

export const MAP_FIGURES: Record<FigureSex, Record<FigureView, MapFigure>> = {
  male: { front: toMapFigure(BODY_FIGURES.male.front, 'front'), back: toMapFigure(BODY_FIGURES.male.back, 'back') },
  female: {
    front: toMapFigure(BODY_FIGURES.female.front, 'front'),
    back: toMapFigure(BODY_FIGURES.female.back, 'back'),
  },
};

const allRegions = (sex: FigureSex) => [...MAP_FIGURES[sex].front.regions, ...MAP_FIGURES[sex].back.regions];

/** Every muscle that lights some region (shared ones included, e.g. abductors). */
export const DRAWN_MUSCLES: ReadonlySet<Muscle> = new Set(
  (Object.keys(MAP_FIGURES) as FigureSex[]).flatMap((sex) => allRegions(sex).flatMap((r) => r.lit)),
);

/** Muscles with a region of their own on this sex's figures. */
export const OWN_REGION_MUSCLES: Record<FigureSex, ReadonlySet<Muscle>> = {
  male: new Set(allRegions('male').map((r) => r.muscle)),
  female: new Set(allRegions('female').map((r) => r.muscle)),
};

/** The figure for the user's `sex` setting: female → female figure, otherwise (male / not set) male. */
export function figureSex(sex: Settings['sex'] | undefined): FigureSex {
  return sex === 'female' ? 'female' : 'male';
}

/**
 * Regions to outline for a selected muscle: its own regions, or — for a muscle that only shares another's region
 * (abductors) — the regions it lights.
 */
export function regionsToOutline(figure: MapFigure, sex: FigureSex, selected: Muscle | null | undefined): MapRegion[] {
  if (!selected) return [];
  const own = OWN_REGION_MUSCLES[sex].has(selected);
  return figure.regions.filter((r) => (own ? r.muscle === selected : r.lit.includes(selected)));
}
