import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { EQUIPMENT, EXERCISE_TYPES, MUSCLES, type CatalogExercise, type ExerciseType } from '../types';

// The catalog is generated by `npm run catalog` (scripts/build-catalog.mjs + scripts/catalog-overrides.json).
// These tests guard the contract the rest of the app relies on.

const root = process.cwd();
const catalog = JSON.parse(readFileSync(join(root, 'src/data/catalog.json'), 'utf8')) as CatalogExercise[];
const source = JSON.parse(readFileSync(join(root, 'scripts/source/free-exercise-db.json'), 'utf8')) as {
  id: string;
  name: string;
}[];
const byName = new Map(catalog.map((e) => [e.name.toLowerCase(), e]));
const find = (name: string) => byName.get(name.toLowerCase());

/** Exercises the owner (and Hevy users) expect to find by exactly these names. */
const MUST_HAVE = [
  'Bench Press (Barbell)',
  'Incline Bench Press (Dumbbell)',
  'Squat (Barbell)',
  'Deadlift (Barbell)',
  'Overhead Press (Barbell)',
  'Pull Up',
  'Chin Up',
  'Push Up',
  'Plank',
  'Lat Pulldown (Cable)',
  'Lat Pulldown (Machine)',
  'Lat Pulldown - Close Grip (Cable)',
  'Single Arm Lat Pulldown (Cable)',
  'Kneeling Pulldown (Cable)',
  'Straight Arm Pulldown (Cable)',
  'Seated Row (Machine)',
  'Seated Cable Row - V Grip (Cable)',
  'Chest Press (Machine)',
  'Incline Chest Press (Machine)',
  'Iso-Lateral Chest Press (Machine)',
  'Iso-Lateral Row (Machine)',
  'Pec Deck (Machine)',
  'Rear Delt Fly (Machine)',
  'Reverse Fly (Dumbbell)',
  'Chest Fly - High to Low (Cable)',
  'Chest Fly - Low to High (Cable)',
  'Face Pull (Cable)',
  'Shoulder Press (Machine)',
  'Lateral Raise (Machine)',
  'Lateral Raise (Cable)',
  'Lateral Raise (Dumbbell)',
  'Hack Squat (Machine)',
  'Pendulum Squat (Machine)',
  'Belt Squat (Machine)',
  'Leg Press (Machine)',
  'Leg Extension (Machine)',
  'Seated Leg Curl (Machine)',
  'Lying Leg Curl (Machine)',
  'Hip Abduction (Machine)',
  'Hip Adduction (Machine)',
  'Hip Thrust (Machine)',
  'Hip Thrust (Smith Machine)',
  'Glute Kickback (Cable)',
  'Glute Kickback (Machine)',
  'Standing Calf Raise (Machine)',
  'Seated Calf Raise (Machine)',
  'Bicep Curl (Dumbbell)',
  'Bicep Curl (Cable)',
  'Bicep Curl (Machine)',
  'Preacher Curl (Machine)',
  'Triceps Pushdown (Cable)',
  'Triceps Extension (Machine)',
  'Overhead Triceps Extension (Cable)',
  'Triceps Dip (Machine)',
  'Assisted Pull Up (Machine)',
  'Assisted Dip (Machine)',
  'Weighted Pull Up',
  'Weighted Dip',
  'T-Bar Row (Machine)',
  'Chest Supported Row (Dumbbell)',
  'Chest Supported Row (Machine)',
  'Romanian Deadlift (Dumbbell)',
  'Bulgarian Split Squat (Dumbbell)',
  'Goblet Squat (Kettlebell)',
  'Goblet Squat (Dumbbell)',
  'Squat (Smith Machine)',
  'Romanian Deadlift (Smith Machine)',
  'Lunge (Smith Machine)',
  'Shrug (Smith Machine)',
  'Shrug (Dumbbell)',
  'Shrug (Barbell)',
  'Upright Row (Barbell)',
  'Upright Row (Cable)',
  'Crunch (Machine)',
  'Crunch (Cable)',
  'Torso Rotation (Machine)',
  'Back Extension (Machine)',
  'Hyperextension',
  'Sled Push',
  'Sled Pull',
  'Treadmill Run',
  'Treadmill Walk',
  'Incline Treadmill Walk',
  'Stair Climber',
  'Stationary Bike',
  'Spin Bike',
  'Elliptical Trainer',
  'Rowing Machine',
  'Air Bike',
  'Jump Rope',
  'Battle Ropes',
  'Burpee',
  'Thruster (Barbell)',
  'Wall Ball',
  'Superman',
];

describe('exercise catalog', () => {
  it('is a reasonably sized library', () => {
    expect(catalog.length).toBeGreaterThan(700);
  });

  it('has unique ids', () => {
    const ids = catalog.map((e) => e.id);
    expect(ids.length - new Set(ids).size).toBe(0);
  });

  it('has unique names (case-insensitive)', () => {
    const seen = new Map<string, string>();
    const dupes: string[] = [];
    for (const e of catalog) {
      const key = e.name.toLowerCase();
      if (seen.has(key)) dupes.push(`${e.name} (${seen.get(key)} / ${e.id})`);
      seen.set(key, e.id);
    }
    expect(dupes).toEqual([]);
  });

  it('never renames ids: every non-added id exists in the source dataset, additions use hv_ snake_case', () => {
    const sourceIds = new Set(source.map((s) => s.id));
    const bad = catalog
      .filter((e) => (e.id.startsWith('hv_') ? !/^hv_[a-z0-9]+(_[a-z0-9]+)*$/.test(e.id) : !sourceIds.has(e.id)))
      .map((e) => e.id);
    expect(bad).toEqual([]);
  });

  it('keeps the original dataset name searchable (name or alias)', () => {
    const sourceName = new Map(source.map((s) => [s.id, s.name]));
    const lost = catalog
      .filter((e) => sourceName.has(e.id))
      .filter((e) => {
        const original = sourceName.get(e.id)!.toLowerCase();
        // Exception: the old name is now ANOTHER exercise's name (dataset "Air Bike" = bicycle crunch, while
        // "Air Bike" is now the fan bike). Searching it must find that exercise, not this one.
        const owner = byName.get(original);
        if (owner && owner.id !== e.id) return false;
        return e.name.toLowerCase() !== original && !(e.aliases ?? []).some((a) => a.toLowerCase() === original);
      })
      .map((e) => e.id);
    expect(lost).toEqual([]);
  });

  it('never uses another exercise\'s name as an alias (search would land on the wrong exercise)', () => {
    const clashes = catalog.flatMap((e) =>
      (e.aliases ?? [])
        .filter((a) => {
          const owner = find(a);
          return owner && owner.id !== e.id;
        })
        .map((a) => `${e.name}: alias "${a}"`),
    );
    expect(clashes).toEqual([]);
    expect(find('Air Bike')?.primary).toBe('cardio');
  });

  it('uses only the vocabularies from src/types.ts', () => {
    const problems: string[] = [];
    for (const e of catalog) {
      if (!(EQUIPMENT as readonly string[]).includes(e.equipment)) problems.push(`${e.id}: equipment ${e.equipment}`);
      if (!(MUSCLES as readonly string[]).includes(e.primary)) problems.push(`${e.id}: primary ${e.primary}`);
      for (const m of e.secondary) {
        if (!(MUSCLES as readonly string[]).includes(m)) problems.push(`${e.id}: secondary ${m}`);
      }
      if (e.secondary.includes(e.primary)) problems.push(`${e.id}: primary repeated in secondary`);
      if (!(EXERCISE_TYPES as readonly string[]).includes(e.type)) problems.push(`${e.id}: type ${e.type}`);
    }
    expect(problems).toEqual([]);
  });

  it('has at least one image per exercise and every image exists under public/', () => {
    const noImages = catalog.filter((e) => !e.images.length).map((e) => e.id);
    expect(noImages).toEqual([]);
    const missing = catalog.flatMap((e) => e.images.filter((p) => !existsSync(join(root, 'public', p))).map((p) => `${e.id}: ${p}`));
    expect(missing).toEqual([]);
  });

  it('has instructions for every exercise', () => {
    const empty = catalog.filter((e) => !e.instructions.length || e.instructions.some((s) => !s.trim())).map((e) => e.id);
    expect(empty).toEqual([]);
  });

  it('gives every cardio exercise a MET value for calorie estimates', () => {
    const noMet = catalog
      .filter((e) => e.primary === 'cardio' || e.equipment === 'cardio')
      .filter((e) => !(typeof e.met === 'number' && e.met > 0))
      .map((e) => e.id);
    expect(noMet).toEqual([]);
  });

  it('only puts a MET on exercises that log time (calories.ts multiplies the MET by logged set time)', () => {
    // A MET on weight_reps / weight_distance etc. would earn 0 kcal AND drop those sets from the strength estimate.
    const timed: ExerciseType[] = ['duration', 'duration_weight', 'distance_duration'];
    expect(catalog.filter((e) => e.met != null && !timed.includes(e.type)).map((e) => `${e.name} [${e.type}]`)).toEqual([]);
    expect(catalog.filter((e) => e.met != null && !(e.met > 0 && e.met < 25)).map((e) => e.id)).toEqual([]);
  });

  it('uses valid level / mechanic / force values', () => {
    const bad = catalog
      .filter(
        (e) =>
          (e.level !== undefined && !['beginner', 'intermediate', 'expert'].includes(e.level)) ||
          (e.mechanic !== undefined && !['compound', 'isolation'].includes(e.mechanic)) ||
          (e.force !== undefined && !['push', 'pull', 'static'].includes(e.force)),
      )
      .map((e) => e.id);
    expect(bad).toEqual([]);
  });

  it('is exactly what `npm run catalog` generates (catalog.json is never hand-edited)', () => {
    const dir = mkdtempSync(join(tmpdir(), 'heft-catalog-'));
    try {
      const out = join(dir, 'catalog.json');
      execFileSync(process.execPath, [join(root, 'scripts/build-catalog.mjs'), '--out', out], { stdio: 'pipe' });
      const fresh = readFileSync(out, 'utf8');
      const committed = readFileSync(join(root, 'src/data/catalog.json'), 'utf8');
      // Line endings are normalised so a CRLF checkout doesn't fail the test.
      expect(committed.replace(/\r\n/g, '\n') === fresh, 'catalog.json is stale: run `npm run catalog`').toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('marks every Smith exercise as smith_machine', () => {
    expect(catalog.filter((e) => /smith/i.test(e.name) && e.equipment !== 'smith_machine').map((e) => e.name)).toEqual([]);
  });

  it('follows the Hevy "<Movement> (<Equipment>)" naming convention', () => {
    const LABEL: Partial<Record<CatalogExercise['equipment'], string>> = {
      barbell: 'Barbell',
      dumbbell: 'Dumbbell',
      machine: 'Machine',
      smith_machine: 'Smith Machine',
      cable: 'Cable',
      kettlebell: 'Kettlebell',
      ez_bar: 'EZ Bar',
      band: 'Band',
      plate: 'Plate',
    };
    const suffixes = Object.values(LABEL).map((l) => `(${l})`);
    const wrong = catalog
      .filter((e) => {
        const label = LABEL[e.equipment];
        return label ? !e.name.endsWith(`(${label})`) : suffixes.some((s) => e.name.endsWith(s));
      })
      .map((e) => `${e.name} [${e.equipment}]`);
    expect(wrong).toEqual([]);
  });

  it('contains the must-have gym exercises', () => {
    expect(MUST_HAVE.filter((n) => !find(n))).toEqual([]);
  });

  it('sets the logging type that matches how each exercise is tracked', () => {
    const expected: [string, ExerciseType][] = [
      ['Bench Press (Barbell)', 'weight_reps'],
      ['Lat Pulldown (Cable)', 'weight_reps'],
      ['Pull Up', 'bodyweight_reps'],
      ['Chin Up', 'bodyweight_reps'],
      ['Push Up', 'bodyweight_reps'],
      ['Triceps Dip', 'bodyweight_reps'],
      ['Sit Up', 'bodyweight_reps'],
      ['Crunch', 'bodyweight_reps'],
      ['Hanging Leg Raise', 'bodyweight_reps'],
      ['Plank', 'duration'],
      ['Side Plank', 'duration'],
      ['Wall Sit', 'duration'],
      ['Weighted Pull Up', 'weighted_bodyweight'],
      ['Weighted Dip', 'weighted_bodyweight'],
      ['Assisted Pull Up (Machine)', 'assisted_bodyweight'],
      ['Assisted Dip (Machine)', 'assisted_bodyweight'],
      ["Farmer's Walk", 'weight_distance'],
      ['Sled Push', 'weight_distance'],
      ['Sled Pull', 'weight_distance'],
      ['Yoke Walk', 'weight_distance'],
      ['Treadmill Run', 'distance_duration'],
      ['Treadmill Walk', 'distance_duration'],
      ['Stationary Bike', 'distance_duration'],
      ['Rowing Machine', 'distance_duration'],
      ['Elliptical Trainer', 'distance_duration'],
      ['Jump Rope', 'duration'],
      ['Battle Ropes', 'duration'],
      ['Stair Climber', 'duration'],
    ];
    const wrong = expected
      .filter(([name, type]) => find(name)?.type !== type)
      .map(([name, type]) => `${name}: expected ${type}, got ${find(name)?.type}`);
    expect(wrong).toEqual([]);
  });

  it('uses Compendium-style MET values for the main cardio machines', () => {
    const met = (name: string) => find(name)?.met;
    expect(met('Treadmill Run')).toBeCloseTo(9.8);
    expect(met('Incline Treadmill Walk')).toBeCloseTo(6.0);
    expect(met('Treadmill Walk')).toBeGreaterThanOrEqual(3.5);
    expect(met('Treadmill Walk')).toBeLessThanOrEqual(4.3);
    expect(met('Stationary Bike')).toBeCloseTo(7.0);
    expect(met('Spin Bike')).toBeCloseTo(8.5);
    expect(met('Elliptical Trainer')).toBeCloseTo(5.0);
    expect(met('Rowing Machine')).toBeCloseTo(7.0);
    expect(met('Stair Climber')).toBeCloseTo(9.0);
    expect(met('Jump Rope')).toBeCloseTo(11.8);
    expect(met('Air Bike')).toBeCloseTo(8.0);
    expect(met('Battle Ropes')).toBeCloseTo(10.3);
  });

  it('puts the right muscles on key exercises', () => {
    expect(find('Lat Pulldown (Cable)')?.primary).toBe('lats');
    expect(find('Bench Press (Barbell)')?.primary).toBe('chest');
    expect(find('Squat (Barbell)')?.primary).toBe('quadriceps');
    expect(find('Hip Abduction (Machine)')?.primary).toBe('abductors');
    expect(find('Hip Adduction (Cable)')?.primary).toBe('adductors');
    expect(find('Bent Over Row (Barbell)')?.primary).toBe('upper_back');
    expect(find('Treadmill Run')?.primary).toBe('cardio');
  });
});
